/*
 *  PRG2201 Object-Oriented Programming JAN 2021
 *  Project - Inventory Management System
 *  Name: Kathryn Lim i21020061 INTI International University Nilai
 * 
 *  [file description]
 */
package inventorymanagementver1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kathryn
 */
public class salesHomepage extends javax.swing.JFrame {

    /**
     * Creates new form salesHomepage
     */
    public salesHomepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salesLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registerSaleButton = new javax.swing.JButton();
        rollbackSaleButton = new javax.swing.JButton();
        displayStocksButton = new javax.swing.JButton();
        displayOOSButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        logout = new javax.swing.JLabel();
        stocksListLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stocksDisplay = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salesLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salesLabel.setText("INVENTORY MANAGEMENT SYSTEM (SALES)");

        jLabel2.setText("Choose Your Action: ");

        registerSaleButton.setText("Register Sale");
        registerSaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerSaleButtonActionPerformed(evt);
            }
        });

        rollbackSaleButton.setText("Rollback Sale");
        rollbackSaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollbackSaleButtonActionPerformed(evt);
            }
        });

        displayStocksButton.setText("Display Stocks");
        displayStocksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayStocksButtonActionPerformed(evt);
            }
        });

        displayOOSButton.setText("Display Out of Stock Items");
        displayOOSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayOOSButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 0, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Logout");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        stocksListLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        stocksListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stocksListLabel.setText("STOCKS LIST");

        stocksDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Description", "Category", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stocksDisplay.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(stocksDisplay);
        if (stocksDisplay.getColumnModel().getColumnCount() > 0) {
            stocksDisplay.getColumnModel().getColumn(0).setResizable(false);
            stocksDisplay.getColumnModel().getColumn(1).setResizable(false);
            stocksDisplay.getColumnModel().getColumn(2).setResizable(false);
            stocksDisplay.getColumnModel().getColumn(3).setResizable(false);
            stocksDisplay.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(salesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(registerSaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rollbackSaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(displayStocksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabel2)))
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(displayOOSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(stocksListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)))))
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salesLabel)
                    .addComponent(logout))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(registerSaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rollbackSaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(displayStocksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(displayOOSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stocksListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerSaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerSaleButtonActionPerformed
       DefaultTableModel display = (DefaultTableModel)stocksDisplay.getModel();
        
    if(stocksDisplay.getSelectionModel().isSelectionEmpty()){
        JOptionPane.showMessageDialog(null, "Please Select a Row!");
    }else{

        int index = stocksDisplay.getSelectedRow(); //gets index of row selected

        //Gets cell values from selected row
        int ID =  Integer.parseInt(display.getValueAt(index,0).toString());

        UserReg.selectedID = ID;

        if(UserReg.productCount != 0){
            UserReg.registerSale.updQty(UserReg.registerSale.search(ID));   //updates quantity count 
            
            UserReg.registerSale.setLocationRelativeTo(null);
            UserReg.registerSale.setVisible(true);
            UserReg.registerSale.clearField();
            this.dispose();
        }
       else
         JOptionPane.showMessageDialog(null, "No products found!"); 
      
      }
        

    }//GEN-LAST:event_registerSaleButtonActionPerformed

    private void rollbackSaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollbackSaleButtonActionPerformed
        if(UserReg.registerSale.saleQty > 0){
            int posn = UserReg.registerSale.selPosn;
            int saleQ = UserReg.registerSale.saleQty;
            
           int input =  JOptionPane.showConfirmDialog(null, "Rollback Previous Sale?", "Undo Sale", JOptionPane.YES_NO_OPTION); //0=YES, 1=NO
            if(input == 0){
                UserReg.products[posn].setQty(UserReg.products[posn].getQty() + saleQ);
                UserReg.registerSale.saleQty = 0;   //resets sale qty
                display();
            }
        }else{
            JOptionPane.showMessageDialog(null, "No record of sales was made");
        }
            
    }//GEN-LAST:event_rollbackSaleButtonActionPerformed

    private void displayStocksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayStocksButtonActionPerformed
        display();
    }//GEN-LAST:event_displayStocksButtonActionPerformed

    private void displayOOSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayOOSButtonActionPerformed
        clearTable();
        DefaultTableModel display = (DefaultTableModel)stocksDisplay.getModel();  
        
        if(UserReg.productCount != 0){
            for(int i = 0; i < UserReg.products.length ; i++){
               if(UserReg.products[i].getQty() == 0){
                   display.addRow(UserReg.products[i].getData());
               } 
            }

            if(display.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "All products are in Stock!");
            }
            
        }
         else
           JOptionPane.showMessageDialog(null, "No products available!");
        
    }//GEN-LAST:event_displayOOSButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    //method to delete all rows in the table
    private void clearTable(){
        DefaultTableModel display = (DefaultTableModel)stocksDisplay.getModel(); 
        
        for(int i = display.getRowCount() - 1; i >= 0; i--){
            display.removeRow(i);
        }
    }
    
    public void display(){
        DefaultTableModel display = (DefaultTableModel)stocksDisplay.getModel(); 
        clearTable();

        if(UserReg.productCount!=0){          
            clearTable();

            for(int i = 0; i < UserReg.productCount; i++){
                display.addRow(UserReg.products[i].getData());
            }
        }else{
                JOptionPane.showMessageDialog(null, "No products found!");
         }  
    }
        
    private int search(int ID){       
        for(int j = 0; j < UserReg.productCount; j++){           
            if(UserReg.products[j].getID() == UserReg.selectedID){
                return j;
            }           
        }        
    return 0;
    }
        
    /**
     * Logout button clicked, displays login page
     * @param evt 
     */  
    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.dispose();
        UserReg.loginPage.setLocationRelativeTo(null);
        UserReg.loginPage.setVisible(true); 
        UserReg.loginPage.clearFields();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salesHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salesHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salesHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salesHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salesHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displayOOSButton;
    private javax.swing.JButton displayStocksButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logout;
    private javax.swing.JButton registerSaleButton;
    private javax.swing.JButton rollbackSaleButton;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JTable stocksDisplay;
    private javax.swing.JLabel stocksListLabel;
    // End of variables declaration//GEN-END:variables
}
